apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/suneelyadava/dlang-http:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/suneelyadava/dlang-http:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: dlang-http
        chartPath: charts/dlang-http
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/suneelyadava/dlang-http"
          image.tag: "{{.TAG}}"
